# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c939c57291be68b8d046427b7fa85fda637a7310a7ac57ba3038f2de3566f2c8df9a24545cb9dc13f8d6c9eb318039184265dc5af638b62fffea75116a15ada

test:
  secret_key_base: e5ef1962d36c215400fb9ad34ce53b58fc150c8f26be9cd5aab711fb24437f390d7b78c10009bd7d2ba25bbb19372239f4157802049acd2834f346aab24b50ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
